import Nav from "@/components/Nav";
import type { Metadata } from "next";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function DashboardLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <div>
         <Nav/>
         <div className={` antialiased`}>{children}</div>
      </div>
   );
}
